### ISSUE TITLE
case insensitive comparison

### ISSUE THREAD

**Issue by atstp** [funcool/cuerdas#22]
Case insensitive comparison would be a pleasant addition to `cuerdas`.

For a function name, my vote would be for `caseless=`.

With respect to locale sensitivity, i'd opt for respecting it. 

  * Java has `equalsIgnoreCase` which is naive to both locale and many unicode nuances; It's good enough for http headers in ring, but maybe not a string library.  An equality check both strings `toLowerCase`d would be the better.  
  * JS doesn't have an case insensitive comparison, but it does have `toLowerCase` and `toLocaleLowerCase` 

I'm up for implementing it it'll be accepted and there's consensus on implementation!

**Comment by niwinz** [comment]
Ok to locale sensitivity but I think it should be optional. By default I'll take the more standard behavior: just lowecase the both and compare. Providing an optional parameter defaulted to false for indicate the intention to use locale aware or something similar.  I'm not clearly convinced about the locale stuff because there are no way to indicate the locale that you want to use, but complete locale awareness is too much for the library.

**Comment by atstp** [comment]
okay, sounds good.  I'll take your opinion on locale into account on the rest the issues I opened.

**Comment by niwinz** [comment]
Hmm, following #21 I think we should put the better. For this concrete case I don't know that is the better default. Maybe instead of parametrized function we can have two function in same way as in #21 one with good modern default and one with the other aproach... 

I don't have clear solution, just my thoughts :P

**Comment by niwinz** [comment]
Done.
