### ISSUE TITLE
Cuerdas interactive documentation

### ISSUE THREAD

**Issue by viebel** [funcool/cuerdas#48]
I see that you have invested a lot of time and thinking in the documentation. And the result is really great.

Take a look at how amazing could be `cuerdas` interactive documentation - using KLIPSE: http://viebel.github.io/klipse/examples/cuerdas.html

Disclaimer: I'm the author of KLIPSE

**Comment by niwinz** [comment]
I know your work on klipse and it is amazing. May main problem is that I didn't have time to try integrate asciidoctor generated doc with klipse but it is already on my list.

**Comment by viebel** [comment]
I could try to make an integration of klipse and asciidoctor.

I've already done it for codox: https://github.com/viebel/codox-klipse-theme

Also, you would need to refactor a bit the code of cuerdas (the macro part) to be self-host compatible :)

**Comment by viebel** [comment]
Meanwhile you could write a blog post - featuring the best features - in order to show to the clojrue[script] community how amazing `cuerdas` is!

**Comment by niwinz** [comment]
About the integration with asciidoctor, if you have time, would be nice to have :D 

About compatibility with self-host, sincerely I know nothing about self host and which changes should be introduced in order to have them compatible.

And about blog, nice idea, I have it on my list, but as you can imagine, this list of to-do things is too much large :(
